/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

Answer: 4613732
*/

#include <iostream>
#include "../utils.h"

int main() {
  // Even Fibonacci numbers:
  // 2, 8, 34, 144, 610, 2584, 10946, ...
  // Follow this relation:
  // e(n) = 4*e(n - 1) + e(n - 2)
  // which can be derived algebraically from the original relation
  Timer timer;
  
  int n1 = 8; int n2 = 2;
  int sum = 2;
  while (n1 <= 4000000) {
    sum += n1;
    int n = 4 * n1 + n2;
    n2 = n1;
    n1 = n;
  }

  timer.printns();

  std::cout << "Answer: " << sum << std::endl;
}